#!/usr/bin/env bash
#
# ops/local-gateway.sh {start|stop|status|test}
#
# Claude Code speaks Anthropic /v1/messages; LM Studio speaks the OpenAI API.
# This runs a LiteLLM proxy on loopback inside the distro to translate between
# them, pointed at LM Studio on the Windows host.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1
# local.env first — see the note in ops/overnight.sh about override precedence.
# shellcheck source=/dev/null
source "$REPO_ROOT/ops/local.env"
# shellcheck source=/dev/null
source "$REPO_ROOT/ops/config.env"

STATE_DIR="$REPO_ROOT/ops/.state"
LOG_DIR="$REPO_ROOT/logs/gateway"
mkdir -p "$STATE_DIR" "$LOG_DIR"
PIDFILE="$STATE_DIR/gateway.pid"
CFG="$STATE_DIR/litellm.yaml"
GWLOG="$LOG_DIR/litellm.log"

say() { printf '  %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# WSL is in NAT mode: the host address changes across restarts, so resolve it
# every time rather than trusting a stored value.
resolve_host() {
  if [ -n "${LMSTUDIO_HOST:-}" ]; then printf '%s' "$LMSTUDIO_HOST"; return; fi
  ip route show default | awk '{print $3}' | head -1
}
lm_base() { printf 'http://%s:%s/v1' "$(resolve_host)" "$LMSTUDIO_PORT"; }
gw_base() { printf 'http://127.0.0.1:%s' "$GATEWAY_PORT"; }

gw_running() {
  [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null
}

check_lmstudio() {
  local base code body
  base="$(lm_base)"
  code=$(curl -s -m 6 -o /dev/null -w '%{http_code}' "$base/models" 2>/dev/null)
  [ "$code" = "200" ] || return 1
  body=$(curl -s -m 6 "$base/models" 2>/dev/null)
  printf '%s' "$body" | grep -q "\"$LMSTUDIO_MODEL\"" || {
    say "WARNING: '$LMSTUDIO_MODEL' not in LM Studio's model list. Loaded models:"
    printf '%s' "$body" | grep -o '"id": *"[^"]*"' | sed 's/.*: *"/    /; s/"$//'
    return 2
  }
  return 0
}

write_config() {
  local base; base="$(lm_base)"
  cat > "$CFG" <<EOF
# Generated by ops/local-gateway.sh — do not edit; regenerated on every start.
# supports_native_streaming: false is REQUIRED, not a tuning knob.
#
# LiteLLM's streaming Anthropic translation drops tool-call arguments: it emits
# content_block_start with "input": {} and then content_block_stop, never
# emitting the input_json_delta events that carry the arguments. Claude Code
# always streams, so every tool call arrives with empty input and the agent
# burns its turns on InputValidationError. Setting this makes LiteLLM call the
# backend non-streaming (where the arguments survive) and synthesize the stream.
# Verified against qwen3.6-35b-a3b on LM Studio, litellm 1.96.2.
model_list:
  - model_name: local-worker
    litellm_params:
      model: openai/${LMSTUDIO_MODEL}
      api_base: ${base}
      api_key: lm-studio
    model_info:
      supports_native_streaming: false
  # Catch-all: Claude Code asks for several model names internally (e.g. a
  # small fast model for background tasks). Route them all to the local model
  # so nothing silently escapes to a paid endpoint or 404s.
  - model_name: "*"
    litellm_params:
      model: openai/${LMSTUDIO_MODEL}
      api_base: ${base}
      api_key: lm-studio
    model_info:
      supports_native_streaming: false

litellm_settings:
  drop_params: true
  telemetry: false

general_settings:
  master_key: ${GATEWAY_KEY}
EOF
}

cmd_start() {
  if gw_running; then say "gateway already running (pid $(cat "$PIDFILE"))"; cmd_status; return 0; fi

  if ! "$GATEWAY_VENV/bin/python" -c "import litellm.proxy.proxy_server" >/dev/null 2>&1; then
    say "LiteLLM proxy not usable at $GATEWAY_VENV — bootstrapping"
    cmd_setup || die "could not install a working LiteLLM proxy"
  fi

  say "LM Studio at $(lm_base) ..."
  check_lmstudio
  case $? in
    0) say "reachable, model '$LMSTUDIO_MODEL' loaded" ;;
    2) say "reachable, but the configured model is not loaded — continuing anyway" ;;
    *) die "cannot reach LM Studio at $(lm_base). Is LM Studio running with the server started, and 'Serve on Local Network' enabled?" ;;
  esac

  write_config
  say "wrote $CFG"

  nohup "$GATEWAY_VENV/bin/litellm" --config "$CFG" \
        --host 127.0.0.1 --port "$GATEWAY_PORT" \
        >>"$GWLOG" 2>&1 &
  echo $! > "$PIDFILE"
  say "litellm starting (pid $(cat "$PIDFILE")), log: $GWLOG"

  local i code
  for i in $(seq 1 60); do
    code=$(curl -s -m 3 -o /dev/null -w '%{http_code}' "$(gw_base)/health/liveliness" 2>/dev/null)
    [ "$code" = "200" ] && { say "gateway healthy after ${i}s"; return 0; }
    gw_running || { say "litellm died on startup — last log lines:"; tail -20 "$GWLOG"; return 1; }
    sleep 1
  done
  say "gateway did not become healthy within 60s — last log lines:"; tail -20 "$GWLOG"
  return 1
}

cmd_stop() {
  if gw_running; then
    kill "$(cat "$PIDFILE")" 2>/dev/null
    sleep 2
    gw_running && kill -9 "$(cat "$PIDFILE")" 2>/dev/null
    say "gateway stopped"
  else
    say "gateway not running"
  fi
  rm -f "$PIDFILE"
}

cmd_status() {
  say "LM Studio:  $(lm_base)"
  say "gateway:    $(gw_base)  [$(gw_running && echo running || echo stopped)]"
  say "model:      $LMSTUDIO_MODEL"
  if gw_running; then
    say "liveliness: $(curl -s -m 3 -o /dev/null -w '%{http_code}' "$(gw_base)/health/liveliness")"
  fi
}

# Send real Anthropic-format requests through the gateway. Streaming tool calls
# are the check that matters — that is the path Claude Code actually uses, and
# the one that silently loses arguments when misconfigured.
#
# max_tokens is deliberately generous: this is a reasoning model that spends
# 100+ tokens thinking before emitting any content, so a small budget returns
# an empty content block and looks like a translation failure.
cmd_test() {
  gw_running || die "gateway not running — start it first"
  local out rc=0

  say "1. plain message ..."
  out=$(curl -s -m 180 -X POST "$(gw_base)/v1/messages" \
        -H 'content-type: application/json' -H "x-api-key: $GATEWAY_KEY" \
        -H 'anthropic-version: 2023-06-01' \
        -d '{"model":"local-worker","max_tokens":1024,"messages":[{"role":"user","content":"Reply with exactly: GATEWAY_OK"}]}' 2>&1)
  if printf '%s' "$out" | grep -q 'GATEWAY_OK'; then
    say "   PASS"
  else
    say "   FAIL: $(printf '%s' "$out" | head -c 400)"; rc=1
  fi

  say "2. STREAMING tool call (the path Claude Code uses) ..."
  out=$(curl -s -N -m 240 -X POST "$(gw_base)/v1/messages" \
        -H 'content-type: application/json' -H "x-api-key: $GATEWAY_KEY" \
        -H 'anthropic-version: 2023-06-01' \
        -d '{"model":"local-worker","max_tokens":1024,"stream":true,"tools":[{"name":"get_weather","description":"Get weather for a city","input_schema":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}],"messages":[{"role":"user","content":"What is the weather in Paris? Use the tool."}]}' 2>&1)
  if printf '%s' "$out" | grep -q 'input_json_delta'; then
    say "   PASS — tool arguments survive streaming"
  else
    say "   FAIL — no input_json_delta events: tool arguments are being dropped."
    say "   Check that model_info.supports_native_streaming is false in $CFG."
    rc=1
  fi

  [ "$rc" = 0 ] || say "see $GWLOG"
  return $rc
}

# Create the venv with the pinned versions this actually works on.
cmd_setup() {
  say "creating $GATEWAY_VENV ..."
  python3 -m venv "$GATEWAY_VENV" 2>/dev/null
  "$GATEWAY_VENV/bin/pip" install -q --upgrade pip
  # litellm 1.96.2 does not import against fastapi >=0.116 (get_flat_dependant
  # was removed); sse-starlette 3.x then demands a starlette newer than the one
  # fastapi <0.116 pins. These two bounds are what make the proxy importable.
  say "installing litellm with pinned fastapi/sse-starlette ..."
  "$GATEWAY_VENV/bin/pip" install -q "litellm[proxy]" "fastapi<0.116" "sse-starlette<3" || return 1
  "$GATEWAY_VENV/bin/python" -c "import litellm.proxy.proxy_server" 2>&1 | tail -3
  "$GATEWAY_VENV/bin/python" -c "import litellm.proxy.proxy_server" >/dev/null 2>&1 \
    && { say "proxy imports cleanly"; return 0; } || { say "proxy still does not import"; return 1; }
}

case "${1:-status}" in
  start)  cmd_start ;;
  stop)   cmd_stop ;;
  status) cmd_status ;;
  test)   cmd_test ;;
  setup)  cmd_setup ;;
  restart) cmd_stop; cmd_start ;;
  *) echo "usage: $0 {setup|start|stop|restart|status|test}" >&2; exit 2 ;;
esac
