#!/usr/bin/env bash
#
# ops/local-gateway.sh {start|stop|status|test}
#
# Claude Code speaks Anthropic /v1/messages; LM Studio speaks the OpenAI API.
# This runs a LiteLLM proxy on loopback inside the distro to translate between
# them, pointed at LM Studio on the Windows host.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1
# shellcheck source=/dev/null
source "$REPO_ROOT/ops/config.env"
# shellcheck source=/dev/null
source "$REPO_ROOT/ops/local.env"

STATE_DIR="$REPO_ROOT/ops/.state"
LOG_DIR="$REPO_ROOT/logs/gateway"
mkdir -p "$STATE_DIR" "$LOG_DIR"
PIDFILE="$STATE_DIR/gateway.pid"
CFG="$STATE_DIR/litellm.yaml"
GWLOG="$LOG_DIR/litellm.log"

say() { printf '  %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# WSL is in NAT mode: the host address changes across restarts, so resolve it
# every time rather than trusting a stored value.
resolve_host() {
  if [ -n "${LMSTUDIO_HOST:-}" ]; then printf '%s' "$LMSTUDIO_HOST"; return; fi
  ip route show default | awk '{print $3}' | head -1
}
lm_base() { printf 'http://%s:%s/v1' "$(resolve_host)" "$LMSTUDIO_PORT"; }
gw_base() { printf 'http://127.0.0.1:%s' "$GATEWAY_PORT"; }

gw_running() {
  [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null
}

check_lmstudio() {
  local base code body
  base="$(lm_base)"
  code=$(curl -s -m 6 -o /dev/null -w '%{http_code}' "$base/models" 2>/dev/null)
  [ "$code" = "200" ] || return 1
  body=$(curl -s -m 6 "$base/models" 2>/dev/null)
  printf '%s' "$body" | grep -q "\"$LMSTUDIO_MODEL\"" || {
    say "WARNING: '$LMSTUDIO_MODEL' not in LM Studio's model list. Loaded models:"
    printf '%s' "$body" | grep -o '"id": *"[^"]*"' | sed 's/.*: *"/    /; s/"$//'
    return 2
  }
  return 0
}

write_config() {
  local base; base="$(lm_base)"
  cat > "$CFG" <<EOF
# Generated by ops/local-gateway.sh — do not edit; regenerated on every start.
model_list:
  - model_name: local-worker
    litellm_params:
      model: openai/${LMSTUDIO_MODEL}
      api_base: ${base}
      api_key: lm-studio
  # Catch-all: Claude Code asks for several model names internally (e.g. a
  # small fast model for background tasks). Route them all to the local model
  # so nothing silently escapes to a paid endpoint or 404s.
  - model_name: "*"
    litellm_params:
      model: openai/${LMSTUDIO_MODEL}
      api_base: ${base}
      api_key: lm-studio

litellm_settings:
  drop_params: true
  telemetry: false

general_settings:
  master_key: ${GATEWAY_KEY}
EOF
}

cmd_start() {
  if gw_running; then say "gateway already running (pid $(cat "$PIDFILE"))"; cmd_status; return 0; fi

  [ -x "$GATEWAY_VENV/bin/litellm" ] || die "LiteLLM not installed at $GATEWAY_VENV. Run: python3 -m venv $GATEWAY_VENV && $GATEWAY_VENV/bin/pip install 'litellm[proxy]'"

  say "LM Studio at $(lm_base) ..."
  check_lmstudio
  case $? in
    0) say "reachable, model '$LMSTUDIO_MODEL' loaded" ;;
    2) say "reachable, but the configured model is not loaded — continuing anyway" ;;
    *) die "cannot reach LM Studio at $(lm_base). Is LM Studio running with the server started, and 'Serve on Local Network' enabled?" ;;
  esac

  write_config
  say "wrote $CFG"

  nohup "$GATEWAY_VENV/bin/litellm" --config "$CFG" \
        --host 127.0.0.1 --port "$GATEWAY_PORT" \
        >>"$GWLOG" 2>&1 &
  echo $! > "$PIDFILE"
  say "litellm starting (pid $(cat "$PIDFILE")), log: $GWLOG"

  local i code
  for i in $(seq 1 60); do
    code=$(curl -s -m 3 -o /dev/null -w '%{http_code}' "$(gw_base)/health/liveliness" 2>/dev/null)
    [ "$code" = "200" ] && { say "gateway healthy after ${i}s"; return 0; }
    gw_running || { say "litellm died on startup — last log lines:"; tail -20 "$GWLOG"; return 1; }
    sleep 1
  done
  say "gateway did not become healthy within 60s — last log lines:"; tail -20 "$GWLOG"
  return 1
}

cmd_stop() {
  if gw_running; then
    kill "$(cat "$PIDFILE")" 2>/dev/null
    sleep 2
    gw_running && kill -9 "$(cat "$PIDFILE")" 2>/dev/null
    say "gateway stopped"
  else
    say "gateway not running"
  fi
  rm -f "$PIDFILE"
}

cmd_status() {
  say "LM Studio:  $(lm_base)"
  say "gateway:    $(gw_base)  [$(gw_running && echo running || echo stopped)]"
  say "model:      $LMSTUDIO_MODEL"
  if gw_running; then
    say "liveliness: $(curl -s -m 3 -o /dev/null -w '%{http_code}' "$(gw_base)/health/liveliness")"
  fi
}

# Send a real Anthropic-format request through the gateway. This is the check
# that matters: it proves the translation layer works end to end.
cmd_test() {
  gw_running || die "gateway not running — start it first"
  say "POST $(gw_base)/v1/messages ..."
  local out
  out=$(curl -s -m 120 -X POST "$(gw_base)/v1/messages" \
        -H 'content-type: application/json' \
        -H "x-api-key: $GATEWAY_KEY" \
        -H 'anthropic-version: 2023-06-01' \
        -d '{"model":"local-worker","max_tokens":64,"messages":[{"role":"user","content":"Reply with exactly: GATEWAY_OK"}]}' 2>&1)
  printf '%s\n' "$out" | head -c 800; echo
  printf '%s' "$out" | grep -q 'GATEWAY_OK' && { say "PASS — Anthropic-format translation works"; return 0; }
  say "FAIL — see response above and $GWLOG"; return 1
}

case "${1:-status}" in
  start)  cmd_start ;;
  stop)   cmd_stop ;;
  status) cmd_status ;;
  test)   cmd_test ;;
  restart) cmd_stop; cmd_start ;;
  *) echo "usage: $0 {start|stop|restart|status|test}" >&2; exit 2 ;;
esac
